Create fdas
katecam-whokie/test-repo pull request #4
Opened 2024-09-08 05:38 UTC by momnpa333

### PR Type

- [ ] 버그수정(Bugfix)
- [ ] 기능개발(Feature)
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [ ] Other… Please describe:

### 요약

### 상세 내용

### 이슈 번호
#3 

### 스크린샷(선택)

2024-09-08 05:38 UTC, ppochaco approved these changes
lgtm

2024-09-08 05:39 UTC, momnpa333 commented on fdas
> +salkfnmasdl
다시 해

2024-09-08 05:39 UTC, gunGeongun commented on fdas
> +dsa
코드 컨벤션에 맞게 작성해주셔야 할 것 같습니다.

2024-09-08 05:39 UTC, momnpa333 commented on fdas
> +vdsa
잘했어

2024-09-08 05:39 UTC, gunGeongun commented on fdas
> +salkfnmasdl
카멜 케이스로 작성해주세요

2024-09-08 05:39 UTC, gunGeongun commented on fdas
> +sdmlfmsa
타입을 명시해주세요

2024-09-08 05:41 UTC, momnpa333 commented on fdas
> +dsa
ㅗㅗㅗ

2024-09-08 05:41 UTC, momnpa333 commented on fdas
> +dsa
반영했습니다

2024-09-08 05:41 UTC, gunGeongun approved these changes

2024-09-08 05:43 UTC, gunGeongun requested changes
test

2024-09-08 05:43 UTC, momnpa333 commented on fdas
> +sdmlfmsa
힝

2024-09-08 05:44 UTC, yso8296 approved these changes
ㅇㅇㅇㅇ

2024-09-08 05:44 UTC, yso8296 commented on fdas
> +dsa
좋아요

2024-09-13 14:56 UTC, hjinshin approved these changes

2024-09-13 14:56 UTC, hjinshin commented on ㅈㅂ
> +ㅂㅈ  ㅂ
bb

2024-09-13 14:58 UTC, closed without merging